version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - 1443:1443

  ilearncorev19:
    image: ${DOCKER_REGISTRY-}ilearncorev19
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db